interface IMakesAndModels {
  [key: string]: string[];
}

export const MAKES_AND_MODELS: IMakesAndModels = {
  "": [],
  BMW: [
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "8 Series",
    "i7",
    "iX",
    "iX M60",
    "M8",
    "X1",
    "X3",
    "X3 PHEV",
    "X4",
    "X4 M",
    "X5",
    "X5 PHEV",
    "X6",
    "X7",
    "XM",
    "Z4 Roadster",
  ],
  Honda: [
    "Accord",
    "Civic",
    "Civic Si",
    "Civic Type R",
    "CR-V",
    "HR-V",
    "Odyssey",
    "Passport",
    "Pilot",
    "Ridgeline",
  ],
  Hyundai: [
    "Elantra",
    "Ioniq 5",
    "Kona",
    "Nexo",
    "Palisade",
    "Santa Fe",
    "Sonata",
    "Tucson",
    "Venue",
  ],
  Mercedes: [
    "A-Class Hatch",
    "A-Class Sedan",
    "C-Class Sedan",
    "CLA Coupe",
    "CLS Coupe",
    "E-Class Coupe",
    "E-Class Sedan",
    "EQB SUV",
    "EQS Sedan",
    "G-Class SUV",
    "GLA SUV",
    "GLB SUV",
    "GLC Coupe",
    "GLC SUV",
    "GLE SUV",
    "GLS SUV",
    "Maybach GLS SUV",
    "Maybach S-Class",
  ],
  Toyota: [
    "4Runner",
    "bZ4X",
    "Camry",
    "Corolla",
    "Cross",
    "Crown",
    "GR",
    "GR86",
    "Hatchback",
    "Highlander",
    "Mirai",
    "Prime",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Supra",
    "Tacoma",
    "Tundra",
    "Venza",
  ],
};

const currentYear = new Date().getFullYear();
export const VEHICLE_YEARS = Array.from(
  { length: 100 },
  (_x, i) => currentYear - i
).map((year) => ({ label: year.toString(), value: year }));
