import AppointmentsTabs from "@components/appointments/shop/appointmentsTabs";
import QuotesShell from "@components/quotes/shell";
import { UserType } from "@prisma/client";
import { getServerAuthSession } from "@server/common/getServerAuthSession";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { TabPanel, TabView, TabViewTabChangeParams } from "primereact/tabview";
import React, { useEffect, useState } from "react";

/**
 * Renders the shop dashboard page
 * Found at route: "shop/dashboard"
 * Contains the quotes (and chat conversations) as well as service requests
 *
 * @author Leon So <34189743+LeonSo7@users.noreply.github.com>
 * @author Timothy Choy <32019738+TimChoy@users.noreply.github.com>
 * @date 02/13/2023
 * @returns The react page for the route "shop/dashboard"
 */
const ShopDashboard: NextPage = () => {
  const [activeIndex, setActiveIndex] = useState(0);
  const router = useRouter();
  const { tab } = router.query;

  useEffect(() => {
    if (typeof tab === "string") {
      if (tab === "quotes") {
        setActiveIndex(0);
      } else if (tab === "service-requests") {
        setActiveIndex(1);
      }
    }
  }, [tab]);

  const handleTabChange = (e: TabViewTabChangeParams) => {
    setActiveIndex(e.index);
  };

  const toggleActiveTab = () => {
    setActiveIndex((activeIndex + 1) % 2);
  };

  return (
    <div>
      <Head>
        <title>{activeIndex === 0 ? "Quotes" : "Service Requests"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabView activeIndex={activeIndex} onTabChange={handleTabChange}>
        <TabPanel header="Quotes">
          <QuotesShell />
        </TabPanel>
        <TabPanel header="Service Requests">
          <AppointmentsTabs toggleActiveTab={toggleActiveTab} />
        </TabPanel>
      </TabView>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);

  if (
    session &&
    session.user.type !== UserType.EMPLOYEE &&
    session.user.type !== UserType.SHOP_OWNER
  ) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default React.memo(ShopDashboard);
