import { UserType } from "@prisma/client";
import { getServerAuthSession } from "@server/common/getServerAuthSession";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { TabPanel, TabView, TabViewTabChangeParams } from "primereact/tabview";
import React, { useEffect, useState } from "react";
import EmployeeTable from "src/components/employees/employeeTable";
import Services from "../../components/manage/services";

const ManageShopTabs = () => {
  const [activeIndex, setActiveIndex] = useState(0);
  const router = useRouter();
  const { tab } = router.query;

  useEffect(() => {
    if (typeof tab === "string") {
      if (tab === "services") {
        setActiveIndex(0);
      } else if (tab === "employees") {
        setActiveIndex(1);
      }
    }
  }, [tab]);

  const handleTabChange = (e: TabViewTabChangeParams) => {
    setActiveIndex(e.index);
  };

  return (
    <div>
      <Head>
        <title>{activeIndex === 0 ? "Services" : "Employees"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabView activeIndex={activeIndex} onTabChange={handleTabChange}>
        <TabPanel header="Services">
          <Services />
        </TabPanel>
        <TabPanel header="Employees">
          <EmployeeTable />
        </TabPanel>
      </TabView>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);

  if (
    session &&
    session.user.type !== UserType.EMPLOYEE &&
    session.user.type !== UserType.SHOP_OWNER
  ) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default React.memo(ManageShopTabs);
