import classNames from "classnames";
import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "primereact/button";
import { Checkbox } from "primereact/checkbox";
import { DataView } from "primereact/dataview";
import { Dropdown } from "primereact/dropdown";
import { InputText } from "primereact/inputtext";
import { Panel } from "primereact/panel";
import { Slider } from "primereact/slider";
import { useState } from "react";
import styles from "../styles/Home.module.css";

interface IFilter {
  name: string;
  key: string;
}

const Home: NextPage = () => {
  const sortByCategories: IFilter[] = [
    { name: "Name A-Z", key: "name" },
    { name: "Location", key: "location" },
  ];
  const filterByPartType: IFilter[] = [
    { name: "OEM", key: "oem" },
    { name: "Aftermarket", key: "aftermarket" },
  ];
  const filterByPartCondition: IFilter[] = [
    { name: "New", key: "new" },
    { name: "Used", key: "used" },
  ];
  const searchFilterList = ["Service", "Shop Name"];

  const [selectedFilters, setSelectedFilters] = useState<IFilter[]>([]);
  const [locationRange, setLocationRange] = useState([1, 50]);

  const [searchFilter, setSearchFilter] = useState("Service");

  const [shops, setShops] = useState(null);

  const onFilterChange = (e: { value: any; checked: boolean }) => {
    let _selectedFilters = [...selectedFilters];
    if (e.checked) {
      _selectedFilters.push(e.value);
    } else {
      for (let i = 0; i < _selectedFilters.length; i++) {
        const selectedFilter = _selectedFilters[i];
        if (selectedFilter && selectedFilter.key === e.value.key) {
          _selectedFilters.splice(i, 1);
          break;
        }
      }
    }
    setSelectedFilters(_selectedFilters);
  };

  const onSearchFilterChange = (e: { value: any }) => {
    setSearchFilter(e.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Sayyara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.filter}>
          <Panel header="Filter By">
            <h5 className={styles.h5Top}>Part Type</h5>
            {filterByPartType.map((category) => {
              return (
                <div key={category.key} className={styles.buttonList}>
                  <Checkbox
                    inputId={category.key}
                    name="category"
                    value={category}
                    onChange={onFilterChange}
                    checked={selectedFilters.some(
                      (item) => item.key === category.key
                    )}
                  />
                  <label className={styles.label} htmlFor={category.key}>
                    {category.name}
                  </label>
                </div>
              );
            })}
            <h5>Part Condition</h5>
            {filterByPartCondition.map((category) => {
              return (
                <div key={category.key} className={styles.buttonList}>
                  <Checkbox
                    inputId={category.key}
                    name="category"
                    value={category}
                    onChange={onFilterChange}
                    checked={selectedFilters.some(
                      (item) => item.key === category.key
                    )}
                  />
                  <label className={styles.label} htmlFor={category.key}>
                    {category.name}
                  </label>
                </div>
              );
            })}
            <h5>
              Location Range (km): [{locationRange[0]} - {locationRange[1]}]
            </h5>
            <Slider
              value={locationRange}
              min={1}
              max={50}
              onChange={(e) => setLocationRange(e.value)}
              range
            />
          </Panel>
        </div>
        <div className={styles.content}>
          <div className={classNames("p-inputgroup", styles.search)}>
            <InputText className={styles.inputtext} placeholder="Search" />
            <Dropdown
              className={styles.dropdown}
              value={searchFilter}
              options={searchFilterList}
              onChange={onSearchFilterChange}
              placeholder="Service"
            />
            <Button label="Search" />
          </div>
          <DataView value={shops} layout="list" />
        </div>
      </div>
    </div>
  );
};

export default Home;
