import type { NextPage } from "next";
import Head from "next/head";
import { Checkbox } from "primereact/checkbox";
import { DataView } from "primereact/dataview";
import { Panel } from "primereact/panel";
import { RadioButton } from "primereact/radiobutton";
import { useState } from "react";
import styles from "../styles/Home.module.css";

interface IFilter {
  name: string;
  key: string;
}

const Home: NextPage = () => {
  const sortByCategories: IFilter[] = [
    { name: "Name A-Z", key: "name" },
    { name: "Location", key: "location" },
  ];
  const filterByServices: IFilter[] = [
    { name: "Oil Change", key: "oil" },
    { name: "Tire Rotation", key: "tire" },
  ];
  const filterByPart: IFilter[] = [
    { name: "New", key: "new" },
    { name: "Third-party", key: "thirdparty" },
  ];
  const [selectedCategory, setSelectedCategory] = useState(sortByCategories[0]);
  const [selectedFilters, setSelectedFilters] = useState<IFilter[]>([]);

  const [shops, setShops] = useState(null);

  const onFilterChange = (e: { value: any; checked: boolean }) => {
    let _selectedFilters = [...selectedFilters];
    if (e.checked) {
      _selectedFilters.push(e.value);
    } else {
      for (let i = 0; i < _selectedFilters.length; i++) {
        const selectedFilter = _selectedFilters[i];
        if (selectedFilter && selectedFilter.key === e.value.key) {
          _selectedFilters.splice(i, 1);
          break;
        }
      }
    }
    setSelectedFilters(_selectedFilters);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Sayyara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.filter}>
          <Panel header="Sort By" toggleable>
            {sortByCategories.map((category) => {
              if (selectedCategory) {
                return (
                  <div key={category.key} className={styles.buttonList}>
                    <RadioButton
                      inputId={category.key}
                      name="category"
                      value={category}
                      onChange={(e) => setSelectedCategory(e.value)}
                      checked={selectedCategory.key === category.key}
                    />
                    <label className={styles.label} htmlFor={category.key}>
                      {category.name}
                    </label>
                  </div>
                );
              }
            })}
          </Panel>
          <Panel header="Filter By" toggleable>
            <h5>Services Offered</h5>
            {filterByServices.map((category) => {
              return (
                <div key={category.key} className={styles.buttonList}>
                  <Checkbox
                    inputId={category.key}
                    name="category"
                    value={category}
                    onChange={onFilterChange}
                    checked={selectedFilters.some(
                      (item) => item.key === category.key
                    )}
                  />
                  <label className={styles.label} htmlFor={category.key}>
                    {category.name}
                  </label>
                </div>
              );
            })}
            <h5>Part Type</h5>
            {filterByPart.map((category) => {
              return (
                <div key={category.key} className={styles.buttonList}>
                  <Checkbox
                    inputId={category.key}
                    name="category"
                    value={category}
                    onChange={onFilterChange}
                    checked={selectedFilters.some(
                      (item) => item.key === category.key
                    )}
                  />
                  <label className={styles.label} htmlFor={category.key}>
                    {category.name}
                  </label>
                </div>
              );
            })}
          </Panel>
        </div>
        <div className={styles.content}>
          <DataView value={shops} layout="list" />
        </div>
      </div>
    </div>
  );
};

export default Home;
