enum AppointmentTypes {
  SET_APPOINTMENT_STATUS = "SET APPOINTMENT STATUS",
  READ_APPOINTMENTS = "CREATE GET APPOINTMENTS",
  SET_APPOINTMENTS = "SET APPOINTMENT LIST",
  CREATE_APPOINTMENT = "CREATE APPOINTMENT",
}

export default AppointmentTypes;
