enum AppointmentTypes {
  SET_APPOINTMENT_STATUS = "SET APPOINTMENT STATUS",
  READ_APPOINTMENTS = "READ APPOINTMENTS",
  SET_APPOINTMENTS = "SET APPOINTMENTS",
  CREATE_APPOINTMENT = "CREATE APPOINTMENT",
}

export default AppointmentTypes;
