enum AuthTypes {
  CREATE_LOGIN = "CREATE LOGIN",
  CREATE_CUSTOMER_SIGN_UP = "CREATE CUSTOMER SIGN UP",
  CREATE_SHOP_OWNER_SIGN_UP = "CREATE SHOP OWNER SIGN UP",
  CREATE_SHOP_EMPLOYEE_SIGN_UP = "CREATE SHOP EMPLOYEE SIGN UP",
  SET_IS_LOGGED_IN = "SET IS LOGGED IN",
  SET_IS_AUTH_DIALOG_OPEN = "SET IS AUTH DIALOG OPEN",
  SET_USER_TYPE = "SET USER TYPE",
}

export default AuthTypes;
