enum AuthTypes {
  CREATE_LOGIN = "CREATE LOGIN",
  CREATE_CUSTOMER_SIGN_UP = "CREATE CUSTOMER SIGN UP",
  CREATE_SHOP_OWNER_SIGN_UP = "CREATE SHOP OWNER SIGN UP",
  CREATE_SHOP_EMPLOYEE_SIGN_UP = "CREATE SHOP EMPLOYEE SIGN UP",
  SET_IS_LOGGED_IN = "SET IS LOGGED IN",
  SET_IS_AUTH_DIALOG_OPEN = "SET IS AUTH DIALOG OPEN",
  SET_USER_SESSION = "SET USER SESSION",
  SET_SHOW_INVALID_LOGIN_TOAST = "SET SHOW INVALID LOGIN TOAST",
  READ_CUSTOMER_VEHICLE_INFO = "READ CUSTOMER VEHICLE INFO",
  SET_CUSTOMER_VEHICLE_INFO = "SET CUSTOMER VEHICLE INFO",
}

export default AuthTypes;
