enum QuoteTypes {
  GET_CUSTOMER_QUOTES = "GET CUSTOMER QUOTES",
  GET_SHOP_QUOTES = "GET SHOP QUOTES",
  UPDATE_INITIAL_STATE = "UPDATE INITIAL STATE",
  CREATE_QUOTE = "CREATE QUOTE",
  ADD_QUOTE_TO_STATE = "ADD QUOTE TO STATE",
  CREATE_MESSAGE = "CREATE MESSAGE",
  SET_SELECTED_CHAT = "SET SELECTED CHAT",
  SET_MESSAGE = "SET MESSAGE",
  INVITE_CUSTOMER = "INVITE CUSTOMER",
  ACCEPT_QUOTE = "ACCEPT QUOTE",
}

export default QuoteTypes;
