enum ServiceTypes {
  SET_SERVICES = "SET SERVICES",
  READ_SERVICES = "CREATE GET SERVICES",
  CREATE_SERVICE = "CREATE SERVICE",
  DELETE_SERVICE = "DELETE SERVICE",
}

export default ServiceTypes;
