enum ShopTypes {
  READ_SHOP_EMPLOYEES = "READ SHOP EMPLOYEES",
  SET_SHOP_EMPLOYEES = "SET SHOP EMPLOYEES",
  READ_SHOP_SERVICES = "READ SHOP SERVICES",
  SET_SHOP_SERVICES = "SET SHOP SERVICES",
  SET_SHOP_STATE = "SET SHOP STATE",
  SET_SHOP_APPOINTMENTS = "SET SHOP APPOINTMENTS",
  READ_SHOP_APPOINTMENTS = "READ SHOP APPOINTMENTS",
}

export default ShopTypes;
